-- Création de la table pour les codes d'activation
create table public.activation_codes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null unique,
  is_used boolean default false,
  used_at timestamp with time zone,
  device_info text -- Optionnel : pour stocker des infos sur l'appareil qui a utilisé le code
);

-- Activer la sécurité RLS (Row Level Security)
alter table public.activation_codes enable row level security;

-- Politique : Tout le monde peut lire les codes (pour vérifier s'ils sont valides)
-- Note : Dans une vraie prod, on pourrait restreindre cela via une Edge Function pour plus de sécurité,
-- mais pour l'instant, l'accès direct est suffisant pour le MVP.
create policy "Enable read access for all users"
on public.activation_codes for select
using (true);

-- Politique : Tout le monde peut mettre à jour un code (pour le marquer comme utilisé)
create policy "Enable update for all users"
on public.activation_codes for update
using (true)
with check (true);

-- Politique : Tout le monde peut insérer des codes (pour que l'admin puisse en créer depuis l'app)
create policy "Enable insert for all users"
on public.activation_codes for insert
with check (true);

-- Insérer quelques codes de test initiaux
insert into public.activation_codes (code, is_used)
values 
  ('AKOHO2024', false),
  ('TANTSAHA2024', false),
  ('MALAGASY2024', false),
  ('VOKATRA2024', false),
  ('FAMBOLENA2024', false);
