// Generated placeholder for Firebase configuration.
// Replace with the real `firebase_options.dart` generated by `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS || Platform.isMacOS) {
      return ios;
    }
    // Fallback
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:android:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'tantsaha2',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:ios:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'tantsaha2',
    storageBucket: '',
    iosClientId: '',
    iosBundleId: '',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:web:000000000000',
    messagingSenderId: '000000000000',
    projectId: 'tantsaha2',
    authDomain: '',
    storageBucket: '',
    measurementId: '',
  );
}
